language: python
python:
  - "2.7"
  - "3.8"
install:
  - bin/install_dependencies.sh

#before_script:
  # We source here since texlive manager state is required
#  - source bin/install_dependencies

script:
  - bin/test.sh
  - bin/build.sh

after_success:
  - bin/deploy.sh
